runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: grpcio
  version: latest

# Skip any non-essential files for uploading during deploys.
skip_files:
- ^venv$